### ISSUE TITLE
Refs finder is linking to /za/act/2014/3 when it should be /za-wc/act/2014/3

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#1089]
See https://edit.laws.africa/places/za-wc/tasks/7602/ and https://edit.laws.africa/places/za-wc/tasks/7603/

**Comment by goose-life** [comment]
This was an intentional decision when working with sub-national legislation: the assumption was that if an Act is referred to it must be national.

We could probably make a plugin for subnational Acts? (thinking of county legislation in Kenya for example)

**Comment by longhotsummer** [comment]
What if we check the database for referenced work in the current place, and then fall back to the country level?

**Comment by goose-life** [comment]
Sounds good! To also catch references to Provincial Acts in by-laws, we could start in the current place, then check its siblings, and finally fall back to the country?

Sortof related, we should also have a recipe for linking references at the end of a project – while WC Acts are being added, they won't link automatically because they don't exist on the system yet (but they will by the end of the project), so it'll fall back to national in the meantime.
