### ISSUE TITLE
Annotations of a respective section disappear when you navigate to that section via Table of contents

### ISSUE THREAD

**Issue by musangowope** [laws-africa/indigo#1626]
One of the issues here is the disappearing annotations of a section when you navigate to that section via the Table of contents
DEMO of issue:
https://www.loom.com/share/53ba0d8e606146a39395109dd13b624a

**Comment by musangowope** [comment]
I can take a look at this aspect of the problem

**Comment by longhotsummer** [comment]
eg. see https://edit.laws.africa/documents/4935/

**Comment by longhotsummer** [comment]
The annotation in question has an anchor ID of:

`att_1__dvs_nn_4__subdvs_nn_1__subdvs_nn_2__subdvs_nn_2__para_Answer:__subpara_Yes:`

That's from (I'm guessing) old markup which no longer exists. The ID of the target is currently:

`att_1__dvs_nn_4__subdvs_nn_1__subdvs_Question4__subpara_nn_1__subpara_Yes`.

This means the anchor is being resolved based on the surrounding text because it can't be matched directly.

So if the fragment being viewed is "zoomed in" closer than `att_1__dvs_nn_4__subdvs_nn_1`, then the anchor cannot be resolved because it can't "zoom out" enough to get `att_1__dvs_nn_4__subdvs_nn_1` and then resolve the anchor based on the text.

**Comment by goose-life** [comment]
Not fixing this
