### ISSUE TITLE
As an editor changing a work's commencement date, I want to be aware that I may need to change the dates of impacted amended and repealed works

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#626]
If the (main) commencement date of a work is updated, amendments made by that work that have already been recorded don't automatically update to having occured on the new date.
This is probably right, because amendments made by a work don't always and only happen on its main commencement date.
If a commencement date was captured incorrectly and caught later (after related works have been linked), whoever is making the correction should probably be shown which dates will now automatically update (coverpage of any documents on work), and importantly which won't, so that they can be manually updated if needed (date/s of amendment/s to other work/s, repeal date/s of other work/s, etc).
Eventually it might be nice to have checkboxes for all the places where this date has already been recorded in relation to this Act at the place where the main commencement date is changed with the option to select all / none / individual ones to be automatically updated at the same time.
For now just a heads-up would be good I think (it doesn't happen all that often).

**Comment by goose-life** [comment]
We could also automatically create a task for the time being:
If a work's commencement date is being updated, and it has related works, and the old date has been given as an amendment/repeal date, create a task to check whether that should be updated.
This would still mean that the person making the change to the commencement date doesn't have instant feedback. (The task could be assigned to the person who made the change and they'd get a notification email?)

**Comment by longhotsummer** [comment]
To ensure I understand this: if the commencement date for a work A changes, it may be necessary to change the amendment or repeal dates for works that work A amends or repeals.

I don't think we can safely automate this, because it's too easy to get it unexpectedly wrong. If the commencement date is being changed, then that should be guided by something/someone, and should be done carefully.

What we could do is, instead, indicate which related works *may* be impacted by the changed (ie. amended and repealed works that have the same expression (or repeal) date as the current commencement date.

**Comment by goose-life** [comment]
You've understood!
That sounds good and right to me. 
It's just important that the person updating the commencement date of work A should be given a heads-up that their change won't automatically carry through to all of work A's related works.

**Comment by longhotsummer** [comment]
The same can be said about the publication date. Changing that will impact amendments (IIRC).

**Comment by goose-life** [comment]
Just going to give a warning
