### ISSUE TITLE
As a user I want to know if something is definitely not commenced

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#647]
as opposed to us just not having the commencement info.

Make it explicit with `not yet commenced` flag in
- [ ] API (?)
- [ ] coverpage
- [ ] work form
- [ ] bulk creation?

**Comment by longhotsummer** [comment]
# Proposal

We have a new non-null boolean field on a Work, `commenced`, which indicates whether the work has commenced or not. 

## UX

* In the Edit work page, add a checkbox "[ ] Work has commenced", defaults to unchecked.
* When the checkbox is checked, the "commencement date" and "commenced by" options are shown.
* If the checkbox is unchecked, the other two options are hidden.
* A new work label "not commenced",  similar to "stub" and "repealed", is shown alongside the work in popups and work detail pages. 
* If uncommenced, a document's coverpage includes the text "Not yet commenced."

## API

* A new work-level API field is added, a boolean "commenced" field.

## Backend

* A new "commenced" boolean field is added to the Work model, non-null. Defaults to False.
* A Django data migration marks this field as True for works with a commencement date, False otherwise.
* When saving a Work, the `save` method enforces the logic `self.commenced = self.commencement_date is not None`

**Comment by longhotsummer** [comment]
An alternative is simply to treat a null commencement date as not commenced. That's the same logic we use for repealed.

In the past, we used null to indicate "we don't know", but I don't think that's required any more. In fact, it's better to say "not commenced" than "we don't know", since we need to give clear guidance to users. We can still introduce a checkbox in the UI to make it explicit, but we don't need to change the database.

**Comment by longhotsummer** [comment]
Based on discussion, I have updated the proposal. It allows us to model:

* commenced, with a date
* commenced, but we don't know the date
* not commenced

**Comment by longhotsummer** [comment]
We need clarity on the semantics (and therefore wording) when `commenced` is True but there is no commencement date. To me, this means we know the work has commenced, but the exact date is not known. It should be considered a "problematic" case, that we should be working to clarify and resolve.

**Comment by longhotsummer** [comment]
Clarified that the wording is "commencement date is unknown"
