### ISSUE TITLE
Adding a new annotation makes it look like it's a reply

### ISSUE THREAD

**Issue by longhotsummer** [laws-africa/indigo#722]
Bug: when adding a new annotation to a document, it is rendered as though it is a reply to a non-existent root annotation.

To reproduce:

1. open any document
2. add a new annotation

What happens:

<img width="186" alt="National Symbols of the Republic of Namibia Act, 2018 @ 2018-12-28 2019-08-19 20-41-09" src="https://user-images.githubusercontent.com/4178542/63290446-b9037900-c2c1-11e9-879c-f2e1728b6c03.png">

What should happen: it should not be rendered as a reply to another annotation.

**Comment by longhotsummer** [comment]
@ro6ley pls can you take a look at this ASAP.

**Comment by ro6ley** [comment]
@longhotsummer fake annotations used to be rendered as empty replies since they had no id as can be seen below:
![image](https://user-images.githubusercontent.com/8082197/63293501-e4da2b00-c2d0-11e9-8b79-a374d35e565e.png)

So on this line https://github.com/laws-africa/indigo/blob/84fe79d454eb2f13cb62dda1660b7f66f6a17eac/indigo_app/static/javascript/indigo/views/annotations.js#L46 I added the check for content to avoid the situation above.

**Comment by ro6ley** [comment]
I have found a solution that involves manually setting a fake comment's `id` field by using the autogenerated `cid` that Backbone generates for models without `id` fields. This way, I eliminate the earlier check that brought the issue, and also render fake comments with unique autogenerated IDs.

Ref: https://devdocs.io/backbone/index#Model-cid

**Comment by longhotsummer** [comment]
This seems like a reasonable work around, nice.
