### ISSUE TITLE
improve commenting experience 

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#793]
make it so I can highlight a piece of text rather than a whole element

**Comment by longhotsummer** [comment]
https://www.w3.org/TR/annotation-model/

**Comment by longhotsummer** [comment]
There are a couple of related issues here:

* how to determine what text is selected - the DOM Range object seems best
* how to save that selection so that it can be re-displayed later, knowing that the text may change slightly -- it's common to highlight a typo which may later be fixed.
* how to show that highlight in the browser

We probably want to prevent selections that would cross element boundaries, because it's very difficult to display the highlight indicator then as a regular HTML tag.

**Comment by longhotsummer** [comment]
# Proposal

## UX

* Users can select arbitrary text, which then triggers the floating comment bubble on the right. Clicking on that creates a new comment linked to the selection (much like it does today). Replies etc. still work as they do today. 
* Users will no longer see the floating comment button alongside chucks of text, they must select text to make a comment.

## Frontend

* When a comment is created from a text selection, the browser's `Range` object is used to determine the start and end anchor points.
* These anchors are serialised using one or more appropriate target selector mechanisms as per https://www.w3.org/TR/annotation-model/#selectors (eg. a nearby ID + xpath)
* These anchors replace (or supplement) the existing annotation anchor attribute.
* When rendering, the range is re-created based on the start and end anchor points and all the text nodes in-between are wrapped in `mark` elements, with a `data-anntn-id` attribute to link it to the annotation object.

## Backend

* Annotation model must be updated to support serialised target (anchor) descriptions
