### ISSUE TITLE
better differ

### ISSUE THREAD

**Issue by goose-life** [laws-africa/indigo#870]
Guidelines:

* an inserted definition should show as such, and not force every subsequent line to "change"
* an inserted subsection should show as such, similar to above
* a heavily changed paragraph should mark the whole thing as changed (?)
* inserting a link should not show the 'tail' of the link as changed

**Comment by longhotsummer** [comment]
Looking at [xmldiff](https://xmldiff.readthedocs.io/en/stable/index.html), some thoughts:

* we may need to tell it to not use (some) attributes for comparison, otherwise it thinks that changing an list item number changes the whole tree
* an `F` of 0.75 seems to work well
* It's not too hard to apply an XSLT to the resulting diff to get it into our HTML-diff format.
* sometimes it generates unnecessary "delete and re-add the same node" changes, unclear why:

```
<span class="akn-num" diff:delete="">(d)</span>
<span class="akn-num" diff:insert="">(d)</span>
```

**Comment by longhotsummer** [comment]
https://edit.laws.africa/documents/3530/ comparing with previous PIT gets very confused.

**Comment by longhotsummer** [comment]
Some notes on making xmldiff work well:

* use eId (or id in html) to tell xmldiff which elements are definitely the same. This has issues for elements numbered sequentially, such as block lists. So, tell it to use ids only for hierarchical elements with actual numbers. Possibly also tables?
* telling xmldiff which elements can contain text (p, listIntroduction, heading, etc.) is crucial. Ensure it has an exhaustive list.
* look into xmldiff does with formatting attributes
